"""classtree

Revision ID: 1668cc090c1a
Revises: c5804d64794b
Create Date: 2023-06-19 21:16:18.110269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1668cc090c1a'
down_revision = 'c5804d64794b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classtree',
    sa.Column('nodeid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('par_id', sa.Integer(), nullable=True),
    sa.Column('child_num', sa.Integer(), nullable=True),
    sa.Column('class_degree', sa.Integer(), nullable=True),
    sa.Column('rank_num', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('nodeid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classtree')
    # ### end Alembic commands ###
