"""add cocode

Revision ID: df6f83eb0e6b
Revises: 1668cc090c1a
Create Date: 2023-07-15 11:31:59.848284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df6f83eb0e6b'
down_revision = '1668cc090c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cocode',
    sa.Column('codeid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=32), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('code_type', sa.String(length=32), nullable=True),
    sa.Column('lang', sa.String(length=32), nullable=True),
    sa.Column('code_desc', sa.TEXT(), nullable=True),
    sa.Column('code1', sa.TEXT(), nullable=True),
    sa.Column('code2', sa.TEXT(), nullable=True),
    sa.Column('code3', sa.TEXT(), nullable=True),
    sa.Column('comments', sa.TEXT(), nullable=True),
    sa.Column('reply', sa.TEXT(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('edit_time', sa.DateTime(), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('hidden', sa.Integer(), nullable=True),
    sa.Column('hidden_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('codeid')
    )
    op.add_column('tasks', sa.Column('rel_codeid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'rel_codeid')
    op.drop_table('cocode')
    # ### end Alembic commands ###
