version: "3.8"

services:
  fastapi_app:
    build: .
    container_name: tm_backend_container
    ports:
      - "8008:8008"
    volumes:
      - .:/tm-backend
      - /tm-backend/.venv  # 这行确保镜像内的 .venv 不被挂载覆盖
    env_file:
      - path: .env # 添加这一行来挂载 .env 文件

    command: ["/tm-backend/.venv/bin/fastapi", "run", "main.py", "--port", "8008", "--host", "0.0.0.0"]
    environment:
      - ENV=production
    restart: always
