"""my first db

Revision ID: 1daee8ea3da1
Revises: 
Create Date: 2024-11-20 22:27:23.501195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1daee8ea3da1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), nullable=False),
    sa.Column('password', sa.VARCHAR(length=500), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=80), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=500), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=200), nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), nullable=False),
    sa.Column('password', sa.VARCHAR(length=500), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=80), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=32), nullable=True),
    sa.Column('location', sa.VARCHAR(length=32), nullable=True),
    sa.Column('bumen', sa.VARCHAR(length=32), nullable=True),
    sa.Column('role', sa.VARCHAR(length=32), nullable=True),
    sa.Column('shuzhi', sa.Float(), nullable=True),
    sa.Column('learn_hour', sa.Float(), nullable=True),
    sa.Column('create_hour', sa.Float(), nullable=True),
    sa.Column('avantar', sa.VARCHAR(length=256), nullable=True),
    sa.Column('desc', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.Column('last_login_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('register')
    # ### end Alembic commands ###
